export const africa = [
  { country: "Algeria", capital: "Algiers", flag: "Africa/Algeria.png" },
  { country: "Angola", capital: "Luanda", flag: "Africa/Angola.png" },
  { country: "Benin", capital: "Porto-Novo", flag: "Africa/Benin.png" },
  { country: "Botswana", capital: "Gaborone", flag: "Africa/Botswana.png" },
  { country: "Burkina Faso", capital: "Ouagadougou", flag: "Africa/BurkinaFaso.png" },
  { country: "Burundi", capital: "Gitega", flag: "Africa/Burundi.png" },
  { country: "Cameroon", capital: "Yaoundé", flag: "Africa/Cameroon.png" },
  { country: "Cape Verde", capital: "Praia", flag: "Africa/CapeVerde.png" },
  { country: "Central African Republic", capital: "Bangui", flag: "Africa/CentralAfricanRepublic.png" },
  { country: "Chad", capital: "N'Djamena", flag: "Africa/Chad.png" },
  { country: "Comoros", capital: "Moroni", flag: "Africa/Comoros.png" },
  { country: "Democratic Republic of the Congo", capital: "Kinshasa", flag: "Africa/DemocraticRepublicOfTheCongo.png" },
  { country: "Djibouti", capital: "Djibouti", flag: "Africa/Djibouti.png" },
  { country: "Egypt", capital: "Cairo", flag: "Africa/Egypt.png" },
  { country: "Equatorial Guinea", capital: "Malabo", flag: "Africa/EquatorialGuinea.png" },
  { country: "Eritrea", capital: "Asmara", flag: "Africa/Eritrea.png" },
  { country: "Eswatini", capital: "Mbabane", flag: "Africa/Eswatini.png" },
  { country: "Ethiopia", capital: "Addis Ababa", flag: "Africa/Ethiopia.png" },
  { country: "Gabon", capital: "Libreville", flag: "Africa/Gabon.png" },
  { country: "Gambia", capital: "Banjul", flag: "Africa/Gambia.png" },
  { country: "Ghana", capital: "Accra", flag: "Africa/Ghana.png" },
  { country: "Guinea", capital: "Conakry", flag: "Africa/Guinea.png" },
  { country: "Guinea-Bissau", capital: "Bissau", flag: "Africa/GuineaBissau.png" },
  { country: "Ivory Coast", capital: "Yamoussoukro", flag: "Africa/IvoryCoast.png" },
  { country: "Kenya", capital: "Nairobi", flag: "Africa/Kenya.png" },
  { country: "Lesotho", capital: "Maseru", flag: "Africa/Lesotho.png" },
  { country: "Liberia", capital: "Monrovia", flag: "Africa/Liberia.png" },
  { country: "Libya", capital: "Tripoli", flag: "Africa/Libya.png" },
  { country: "Madagascar", capital: "Antananarivo", flag: "Africa/Madagascar.png" },
  { country: "Malawi", capital: "Lilongwe", flag: "Africa/Malawi.png" },
  { country: "Mali", capital: "Bamako", flag: "Africa/Mali.png" },
  { country: "Mauritania", capital: "Nouakchott", flag: "Africa/Mauritania.png" },
  { country: "Mauritius", capital: "Port Louis", flag: "Africa/Mauritius.png" },
  { country: "Morocco", capital: "Rabat", flag: "Africa/Morocco.png" },
  { country: "Mozambique", capital: "Maputo", flag: "Africa/Mozambique.png" },
  { country: "Namibia", capital: "Windhoek", flag: "Africa/Namibia.png" },
  { country: "Niger", capital: "Niamey", flag: "Africa/Niger.png" },
  { country: "Nigeria", capital: "Abuja", flag: "Africa/Nigeria.png" },
  { country: "Republic of the Congo", capital: "Brazzaville" , flag: "Africa/RepublicOfTheCongo.png"},
  { country: "Rwanda", capital: "Kigali", flag: "Africa/Rwanda.png" },
  { country: "São Tomé and Príncipe", capital: "São Tomé", flag: "Africa/SaoTomeAndPrincipe.png" },
  { country: "Senegal", capital: "Dakar", flag: "Africa/Senegal.png" },
  { country: "Seychelles", capital: "Victoria", flag: "Africa/Seychelles.png" },
  { country: "Sierra Leone", capital: "Freetown", flag: "Africa/SierraLeone.png" },
  { country: "Somalia", capital: "Mogadishu", flag: "Africa/Somalia.png" },
  { country: "South Africa", capital: "Pretoria", flag: "Africa/SouthAfrica.png" },
  { country: "South Sudan", capital: "Juba", flag: "Africa/SouthSudan.png" },
  { country: "Sudan", capital: "Khartoum", flag: "Africa/Sudan.png" },
  { country: "Tanzania", capital: "Dodoma", flag: "Africa/Tanzania.png" },
  { country: "Togo", capital: "Lomé", flag: "Africa/Togo.png" },
  { country: "Tunisia", capital: "Tunis", flag: "Africa/Tunisia.png" },
  { country: "Uganda", capital: "Kampala", flag: "Africa/Uganda.png" },
  { country: "Zambia", capital: "Lusaka", flag: "Africa/Zambia.png" },
  { country: "Zimbabwe", capital: "Harare", flag: "Africa/Zimbabwe.png" }
];