export const asia = [
  { country: "Afghanistan", capital: "Kabul", flag: "Asia/Afghanistan.png" },
  { country: "Bahrain", capital: "Manama", flag: "Asia/Bahrain .png" },
  { country: "Bangladesh", capital: "Dhaka", flag: "Asia/Bangladesh.png" },
  { country: "Bhutan", capital: "Thimphu", flag: "Asia/Bhutan .png" },
  { country: "Brunei", capital: "Bandar Seri Begawan", flag: "Asia/Brunei.png" },
  { country: "Cambodia", capital: "Phnom Penh", flag: "Asia/Cambodia.png" },
  { country: "China", capital: "Beijing", flag: "Asia/China.png" },
  { country: "East Timor", capital: "Dili", flag: "Asia/EastTimor.png" },
  { country: "India", capital: "New Delhi", flag: "Asia/India.png" },
  { country: "Indonesia", capital: "Jakarta", flag: "Asia/Indonesia.png" },
  { country: "Iran", capital: "Tehran", flag: "Asia/Iran.png" },
  { country: "Iraq", capital: "Baghdad", flag: "Asia/Iraq.png" },
  { country: "Israel", capital: "Jerusalem", flag: "Asia/Israel.png" },
  { country: "Japan", capital: "Tokyo", flag: "Asia/Japan.png" },
  { country: "Jordan", capital: "Amman", flag: "Asia/Jordan.png" },
  { country: "Kazakhstan", capital: "Astana", flag: "Asia/Kazakhstan.png" },
  { country: "Kuwait", capital: "Kuwait City", flag: "Asia/Kuwait.png" },
  { country: "Kyrgyzstan", capital: "Bishkek", flag: "Asia/Kyrgyzstan.png" },
  { country: "Laos", capital: "Vientiane", flag: "Asia/Laos.png" },
  { country: "Lebanon", capital: "Beirut", flag: "Asia/Lebanon.png" },
  { country: "Malaysia", capital: "Kuala Lumpur", flag: "Asia/Malaysia.png" },
  { country: "Maldives", capital: "Malé", flag: "Asia/Maldives.png" },
  { country: "Mongolia", capital: "Ulaanbaatar", flag: "Asia/Mongolia.png" },
  { country: "Myanmar", capital: "Naypyidaw", flag: "Asia/Myanmar.png" },
  { country: "Nepal", capital: "Kathmandu", flag: "Asia/Nepal.png" },
  { country: "North Korea", capital: "Pyongyang", flag: "Asia/NorthKorea.png" },
  { country: "Oman", capital: "Muscat", flag: "Asia/Oman.png" },
  { country: "Pakistan", capital: "Islamabad", flag: "Asia/Pakistan.png" },
  { country: "Palestine", capital: "Ramallah", flag: "Asia/Palestine.png" },
  { country: "Philippines", capital: "Manila", flag: "Asia/Philippines.png" },
  { country: "Qatar", capital: "Doha", flag: "Asia/Qatar.png" },
  { country: "Saudi Arabia", capital: "Riyadh", flag: "Asia/SaudiArabia.png" },
  { country: "Singapore", capital: "Singapore", flag: "Asia/Singapore.png" },
  { country: "South Korea", capital: "Seoul", flag: "Asia/SouthKorea.png" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", flag: "Asia/SriLanka.png" },
  { country: "Syria", capital: "Damascus", flag: "Asia/Syria.png" },
  { country: "Taiwan", capital: "Taipei", flag: "Asia/Taiwan.png"},
  { country: "Tajikistan", capital: "Dushanbe", flag: "Asia/Tajikistan.png" },
  { country: "Thailand", capital: "Bangkok", flag: "Asia/Thailand.png" },
  { country: "Turkmenistan", capital: "Ashgabat", flag: "Asia/Turkmenistan.png" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", flag: "Asia/UnitedArabEmirates.png" },
  { country: "Uzbekistan", capital: "Tashkent", flag: "Asia/Uzbekistan.png" },
  { country: "Vietnam", capital: "Hanoi", flag: "Asia/Vietnam.png" },
  { country: "Yemen", capital: "Sana'a", flag: "Asia/Yemen.png" }
];