export const europe = [
  { country: "Albania", capital: "Tirana", flag: "Europe/Albania.png" },
  { country: "Andorra", capital: "Andorra la Vella", flag: "Europe/Andorra.png" },
  { country: "Armenia", capital: "Yerevan", flag: "Europe/Armenia.png" },
  { country: "Austria", capital: "Vienna", flag: "Europe/Austria.png" },
  { country: "Azerbaijan", capital: "Baku", flag: "Europe/Azerbaijan.png" },
  { country: "Belarus", capital: "Minsk", flag: "Europe/Belarus.png" },
  { country: "Belgium", capital: "Brussels", flag: "Europe/Belgium.png" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", flag: "Europe/BosniaAndHerzegovina.png" },
  { country: "Bulgaria", capital: "Sofia", flag: "Europe/Bulgaria.png" },
  { country: "Croatia", capital: "Zagreb", flag: "Europe/Croatia.png" },
  { country: "Cyprus", capital: "Nicosia", flag: "Europe/Cyprus.png" },
  { country: "Czech Republic", capital: "Prague", flag: "Europe/CzechRepublic.png" },
  { country: "Denmark", capital: "Copenhagen", flag: "Europe/Denmark.png" },
  { country: "Estonia", capital: "Tallinn", flag: "Europe/Estonia.png" },
  { country: "Finland", capital: "Helsinki", flag: "Europe/Finland.png" },
  { country: "France", capital: "Paris", flag: "Europe/France.png" },
  { country: "Georgia", capital: "Tbilisi", flag: "Europe/Georgia.png" },
  { country: "Germany", capital: "Berlin", flag: "Europe/Germany.png" },
  { country: "Greece", capital: "Athens", flag: "Europe/Greece.png" },
  { country: "Hungary", capital: "Budapest", flag: "Europe/Hungary.png" },
  { country: "Iceland", capital: "Reykjavík", flag: "Europe/Iceland.png" },
  { country: "Ireland", capital: "Dublin", flag: "Europe/Ireland.png" },
  { country: "Italy", capital: "Rome", flag: "Europe/Italy.png" },
  { country: "Kosovo", capital: "Pristina", flag: "Europe/Kosovo.png" },
  { country: "Latvia", capital: "Riga", flag: "Europe/Latvia.png" },
  { country: "Liechtenstein", capital: "Vaduz", flag: "Europe/Liechtenstein.png" },
  { country: "Lithuania", capital: "Vilnius", flag: "Europe/Lithuania.png" },
  { country: "Luxembourg", capital: "Luxembourg", flag: "Europe/Luxembourg.png" },
  { country: "Malta", capital: "Valletta", flag: "Europe/Malta.png" },
  { country: "Moldova", capital: "Chișinău", flag: "Europe/Moldova.png" },
  { country: "Monaco", capital: "Monaco", flag: "Europe/Monaco.png" },
  { country: "Montenegro", capital: "Podgorica", flag: "Europe/Montenegro.png" },
  { country: "Netherlands", capital: "Amsterdam", flag: "Europe/Netherlands.png" },
  { country: "North Macedonia", capital: "Skopje", flag: "Europe/NorthMacedonia.png" },
  { country: "Norway", capital: "Oslo", flag: "Europe/Norway.png" },
  { country: "Poland", capital: "Warsaw", flag: "Europe/Poland.png" },
  { country: "Portugal", capital: "Lisbon", flag: "Europe/Portugal.png" },
  { country: "Romania", capital: "Bucharest", flag: "Europe/Romania.png" },
  { country: "Russia", capital: "Moscow", flag: "Europe/Russia.png" },
  { country: "San Marino", capital: "San Marino", flag: "Europe/SanMarino.png" },
  { country: "Serbia", capital: "Belgrade", flag: "Europe/Serbia.png" },
  { country: "Slovakia", capital: "Bratislava", flag: "Europe/Slovakia.png" },
  { country: "Slovenia", capital: "Ljubljana", flag: "Europe/Slovenia.png" },
  { country: "Spain", capital: "Madrid", flag: "Europe/Spain.png" },
  { country: "Sweden", capital: "Stockholm", flag: "Europe/Sweden.png" },
  { country: "Switzerland", capital: "Bern", flag: "Europe/Switzerland.png" },
  { country: "Turkey", capital: "Ankara", flag: "Europe/Turkey.png" },
  { country: "Ukraine", capital: "Kyiv", flag: "Europe/Ukraine.png" },
  { country: "United Kingdom", capital: "London", flag: "Europe/UnitedKingdom.png" },
  { country: "Vatican City", capital: "Vatican City", flag: "Europe/VaticanCity.png" }
];