export const northAmerica = [
  { country: "Antigua and Barbuda", capital: "Saint John's", flag: "NorthAmerica/AntiguaAndBarbuda.png" },
  { country: "Bahamas", capital: "Nassau", flag: "NorthAmerica/Bahamas.png" },
  { country: "Barbados", capital: "Bridgetown", flag: "NorthAmerica/Barbados.png" },
  { country: "Belize", capital: "Belmopan", flag: "NorthAmerica/Belize.png" },
  { country: "Canada", capital: "Ottawa", flag: "NorthAmerica/Canada.png" },
  { country: "Costa Rica", capital: "San José", flag: "NorthAmerica/CostaRica.png" },
  { country: "Cuba", capital: "Havana", flag: "NorthAmerica/Cuba.png" },
  { country: "Dominica", capital: "Roseau", flag: "NorthAmerica/Dominica.png" },
  { country: "Dominican Republic", capital: "Santo Domingo", flag: "NorthAmerica/DominicanRepublic.png" },
  { country: "El Salvador", capital: "San Salvador", flag: "NorthAmerica/ElSalvador.png" },
  { country: "Grenada", capital: "St. George's", flag: "NorthAmerica/Grenada.png" },
  { country: "Guatemala", capital: "Guatemala City", flag: "NorthAmerica/Guatemala.png" },
  { country: "Haiti", capital: "Port-au-Prince", flag: "NorthAmerica/Haiti.png" },
  { country: "Honduras", capital: "Tegucigalpa", flag: "NorthAmerica/Honduras.png" },
  { country: "Jamaica", capital: "Kingston", flag: "NorthAmerica/Jamaica.png" },
  { country: "Mexico", capital: "Mexico City", flag: "NorthAmerica/Mexico.png" },
  { country: "Nicaragua", capital: "Managua", flag: "NorthAmerica/Nicaragua.png" },
  { country: "Panama", capital: "Panama City", flag: "NorthAmerica/Panama.png" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre", flag: "NorthAmerica/SaintKittsAndNevis.png" },
  { country: "Saint Lucia", capital: "Castries", flag: "NorthAmerica/SaintLucia.png" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", flag: "NorthAmerica/SaintVincentAndTheGrenadines.png" },
  { country: "Trinidad and Tobago", capital: "Port of Spain", flag: "NorthAmerica/TrinidadAndTobago.png" },
  { country: "United States of America", capital: "Washington D.C.", flag: "NorthAmerica/UnitedStatesOfAmerica.png" }
];