export const world = [
  // North America
  { country: "Antigua and Barbuda", capital: "Saint John's", flag: "NorthAmerica/AntiguaAndBarbuda.png" },
  { country: "Bahamas", capital: "Nassau", flag: "NorthAmerica/Bahamas.png" },
  { country: "Barbados", capital: "Bridgetown", flag: "NorthAmerica/Barbados.png" },
  { country: "Belize", capital: "Belmopan", flag: "NorthAmerica/Belize.png" },
  { country: "Canada", capital: "Ottawa", flag: "NorthAmerica/Canada.png" },
  { country: "Costa Rica", capital: "San José", flag: "NorthAmerica/CostaRica.png" },
  { country: "Cuba", capital: "Havana", flag: "NorthAmerica/Cuba.png" },
  { country: "Dominica", capital: "Roseau", flag: "NorthAmerica/Dominica.png" },
  { country: "Dominican Republic", capital: "Santo Domingo", flag: "NorthAmerica/DominicanRepublic.png" },
  { country: "El Salvador", capital: "San Salvador", flag: "NorthAmerica/ElSalvador.png" },
  { country: "Grenada", capital: "St. George's", flag: "NorthAmerica/Grenada.png" },
  { country: "Guatemala", capital: "Guatemala City", flag: "NorthAmerica/Guatemala.png" },
  { country: "Haiti", capital: "Port-au-Prince", flag: "NorthAmerica/Haiti.png" },
  { country: "Honduras", capital: "Tegucigalpa", flag: "NorthAmerica/Honduras.png" },
  { country: "Jamaica", capital: "Kingston", flag: "NorthAmerica/Jamaica.png" },
  { country: "Mexico", capital: "Mexico City", flag: "NorthAmerica/Mexico.png" },
  { country: "Nicaragua", capital: "Managua", flag: "NorthAmerica/Nicaragua.png" },
  { country: "Panama", capital: "Panama City", flag: "NorthAmerica/Panama.png" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre", flag: "NorthAmerica/SaintKittsAndNevis.png" },
  { country: "Saint Lucia", capital: "Castries", flag: "NorthAmerica/SaintLucia.png" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", flag: "NorthAmerica/SaintVincentAndTheGrenadines.png" },
  { country: "Trinidad and Tobago", capital: "Port of Spain", flag: "NorthAmerica/TrinidadAndTobago.png" },
  { country: "United States of America", capital: "Washington D.C.", flag: "NorthAmerica/UnitedStatesOfAmerica.png" },

  // South America
  { country: "Argentina", capital: "Buenos Aires", flag: "SouthAmerica/Argentina.png" },
  { country: "Bolivia", capital: "Sucre", flag: "SouthAmerica/Bolivia.png" },
  { country: "Brazil", capital: "Brasília" },
  { country: "Chile", capital: "Santiago", flag: "SouthAmerica/Chile.png" },
  { country: "Colombia", capital: "Bogotá", flag: "SouthAmerica/Colombia.png" },
  { country: "Ecuador", capital: "Quito", flag: "SouthAmerica/Ecuador.png" },
  { country: "Guyana", capital: "Georgetown", flag: "SouthAmerica/Guyana.png" },
  { country: "Paraguay", capital: "Asunción", flag: "SouthAmerica/Paraguay.png" },
  { country: "Peru", capital: "Lima", flag: "SouthAmerica/Peru.png" },
  { country: "Suriname", capital: "Paramaribo", flag: "SouthAmerica/Suriname.png" },
  { country: "Uruguay", capital: "Montevideo", flag: "SouthAmerica/Uruguay.png" },
  { country: "Venezuela", capital: "Caracas", flag: "SouthAmerica/Venezuela.png" },

  // Europe
  { country: "Albania", capital: "Tirana", flag: "Europe/Albania.png" },
  { country: "Andorra", capital: "Andorra la Vella", flag: "Europe/Andorra.png" },
  { country: "Armenia", capital: "Yerevan", flag: "Europe/Armenia.png" },
  { country: "Austria", capital: "Vienna", flag: "Europe/Austria.png" },
  { country: "Azerbaijan", capital: "Baku", flag: "Europe/Azerbaijan.png" },
  { country: "Belarus", capital: "Minsk", flag: "Europe/Belarus.png" },
  { country: "Belgium", capital: "Brussels", flag: "Europe/Belgium.png" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", flag: "Europe/BosniaAndHerzegovina.png" },
  { country: "Bulgaria", capital: "Sofia", flag: "Europe/Bulgaria.png" },
  { country: "Croatia", capital: "Zagreb", flag: "Europe/Croatia.png" },
  { country: "Cyprus", capital: "Nicosia", flag: "Europe/Cyprus.png" },
  { country: "Czech Republic", capital: "Prague", flag: "Europe/CzechRepublic.png" },
  { country: "Denmark", capital: "Copenhagen", flag: "Europe/Denmark.png" },
  { country: "Estonia", capital: "Tallinn", flag: "Europe/Estonia.png" },
  { country: "Finland", capital: "Helsinki", flag: "Europe/Finland.png" },
  { country: "France", capital: "Paris", flag: "Europe/France.png" },
  { country: "Georgia", capital: "Tbilisi", flag: "Europe/Georgia.png" },
  { country: "Germany", capital: "Berlin", flag: "Europe/Germany.png" },
  { country: "Greece", capital: "Athens", flag: "Europe/Greece.png" },
  { country: "Hungary", capital: "Budapest", flag: "Europe/Hungary.png" },
  { country: "Iceland", capital: "Reykjavík", flag: "Europe/Iceland.png" },
  { country: "Ireland", capital: "Dublin", flag: "Europe/Ireland.png" },
  { country: "Italy", capital: "Rome", flag: "Europe/Italy.png" },
  { country: "Kazakhstan", capital: "Astana", flag: "Europe/Kazakhstan.png" },
  { country: "Kosovo", capital: "Pristina", flag: "Europe/Kosovo.png" },
  { country: "Latvia", capital: "Riga", flag: "Europe/Latvia.png" },
  { country: "Liechtenstein", capital: "Vaduz", flag: "Europe/Liechtenstein.png" },
  { country: "Lithuania", capital: "Vilnius", flag: "Europe/Lithuania.png" },
  { country: "Luxembourg", capital: "Luxembourg", flag: "Europe/Luxembourg.png" },
  { country: "Malta", capital: "Valletta", flag: "Europe/Malta.png" },
  { country: "Moldova", capital: "Chișinău", flag: "Europe/Moldova.png" },
  { country: "Monaco", capital: "Monaco", flag: "Europe/Monaco.png" },
  { country: "Montenegro", capital: "Podgorica", flag: "Europe/Montenegro.png" },
  { country: "Netherlands", capital: "Amsterdam", flag: "Europe/Netherlands.png" },
  { country: "North Macedonia", capital: "Skopje", flag: "Europe/NorthMacedonia.png" },
  { country: "Norway", capital: "Oslo" },
  { country: "Poland", capital: "Warsaw", flag: "Europe/Poland.png" },
  { country: "Portugal", capital: "Lisbon", flag: "Europe/Portugal.png" },
  { country: "Romania", capital: "Bucharest", flag: "Europe/Romania.png" },
  { country: "Russia", capital: "Moscow", flag: "Europe/Russia.png" },
  { country: "San Marino", capital: "San Marino", flag: "Europe/SanMarino.png" },
  { country: "Serbia", capital: "Belgrade", flag: "Europe/Serbia.png" },
  { country: "Slovakia", capital: "Bratislava", flag: "Europe/Slovakia.png" },
  { country: "Slovenia", capital: "Ljubljana", flag: "Europe/Slovenia.png" },
  { country: "Spain", capital: "Madrid", flag: "Europe/Spain.png" },
  { country: "Sweden", capital: "Stockholm", flag: "Europe/Sweden.png" },
  { country: "Switzerland", capital: "Bern", flag: "Europe/Switzerland.png" },
  { country: "Turkey", capital: "Ankara", flag: "Europe/Turkey.png" },
  { country: "Ukraine", capital: "Kyiv", flag: "Europe/Ukraine.png" },
  { country: "United Kingdom", capital: "London", flag: "Europe/UnitedKingdom.png" },
  { country: "Vatican City", capital: "Vatican City", flag: "Europe/VaticanCity.png" },

  // Africa
  { country: "Algeria", capital: "Algiers", flag: "Africa/Algeria.png" },
  { country: "Angola", capital: "Luanda", flag: "Africa/Angola.png" },
  { country: "Benin", capital: "Porto-Novo", flag: "Africa/Benin.png" },
  { country: "Botswana", capital: "Gaborone", flag: "Africa/Botswana.png" },
  { country: "Burkina Faso", capital: "Ouagadougou", flag: "Africa/BurkinaFaso.png" },
  { country: "Burundi", capital: "Gitega", flag: "Africa/Burundi.png" },
  { country: "Cabo Verde", capital: "Praia", flag: "Africa/CaboVerde.png" },
  { country: "Cameroon", capital: "Yaoundé", flag: "Africa/Cameroon.png" },
  { country: "Central African Republic", capital: "Bangui", flag: "Africa/CentralAfricanRepublic.png" },
  { country: "Chad", capital: "N'Djamena", flag: "Africa/Chad.png" },
  { country: "Comoros", capital: "Moroni", flag: "Africa/Comoros.png" },
  { country: "Republic of the Congo", capital: "Brazzaville" , flag: "Africa/RepublicOfTheCongo.png"},
  { country: "Democratic Republic of the Congo", capital: "Kinshasa", flag: "Africa/DemocraticRepublicOfTheCongo.png" },
  { country: "Djibouti", capital: "Djibouti", flag: "Africa/Djibouti.png" },
  { country: "Egypt", capital: "Cairo", flag: "Africa/Egypt.png" },
  { country: "Equatorial Guinea", capital: "Malabo", flag: "EquatorialGuinea.png" },
  { country: "Eritrea", capital: "Asmara", flag: "Africa/Eritrea.png" },
  { country: "Eswatini", capital: "Mbabane", flag: "Africa/Eswatini.png" },
  { country: "Ethiopia", capital: "Addis Ababa", flag: "Africa/Ethiopia.png" },
  { country: "Gabon", capital: "Libreville", flag: "Africa/Gabon.png" },
  { country: "Gambia", capital: "Banjul", flag: "Africa/Gambia.png" },
  { country: "Ghana", capital: "Accra", flag: "Africa/Ghana.png" },
  { country: "Guinea", capital: "Conakry", flag: "Africa/Guinea.png" },
  { country: "Guinea-Bissau", capital: "Bissau", flag: "GuineaBissau.png" },
  { country: "Ivory Coast", capital: "Yamoussoukro", flag: "Africa/IvoryCoast.png" },
  { country: "Kenya", capital: "Nairobi", flag: "Africa/Kenya.png" },
  { country: "Lesotho", capital: "Maseru", flag: "Africa/Lesotho.png" },
  { country: "Liberia", capital: "Monrovia", flag: "Africa/Liberia.png" },
  { country: "Libya", capital: "Tripoli", flag: "Africa/Libya.png" },
  { country: "Madagascar", capital: "Antananarivo", flag: "Africa/Madagascar.png" },
  { country: "Malawi", capital: "Lilongwe", flag: "Africa/Malawi.png" },
  { country: "Mali", capital: "Bamako", flag: "Africa/Mali.png" },
  { country: "Mauritania", capital: "Nouakchott", flag: "Africa/Mauritania.png" },
  { country: "Mauritius", capital: "Port Louis", flag: "Africa/Mauritius.png" },
  { country: "Morocco", capital: "Rabat", flag: "Africa/Morocco.png" },
  { country: "Mozambique", capital: "Maputo", flag: "Africa/Mozambique.png" },
  { country: "Namibia", capital: "Windhoek", flag: "Africa/Namibia.png" },
  { country: "Niger", capital: "Niamey", flag: "Africa/Niger.png" },
  { country: "Nigeria", capital: "Abuja", flag: "Africa/Nigeria.png" },
  { country: "Rwanda", capital: "Kigali", flag: "Africa/Rwanda.png" },
  { country: "São Tomé and Príncipe", capital: "São Tomé", flag: "Africa/SaoTomeAndPrincipe.png" },
  { country: "Senegal", capital: "Dakar", flag: "Africa/Senegal.png" },
  { country: "Seychelles", capital: "Victoria", flag: "Africa/Seychelles.png" },
  { country: "Sierra Leone", capital: "Freetown", flag: "Africa/SierraLeone.png" },
  { country: "Somalia", capital: "Mogadishu", flag: "Africa/Somalia.png" },
  { country: "South Africa", capital: "Pretoria", flag: "Africa/SouthAfrica.png" },
  { country: "South Sudan", capital: "Juba", flag: "Africa/SouthSudan.png" },
  { country: "Sudan", capital: "Khartoum", flag: "Africa/Sudan.png" },
  { country: "Tanzania", capital: "Dodoma", flag: "Africa/Tanzania.png" },
  { country: "Togo", capital: "Lomé", flag: "Africa/Togo.png" },
  { country: "Tunisia", capital: "Tunis", flag: "Africa/Tunisia.png" },
  { country: "Uganda", capital: "Kampala", flag: "Africa/Uganda.png" },
  { country: "Zambia", capital: "Lusaka", flag: "Africa/Zambia.png" },
  { country: "Zimbabwe", capital: "Harare", flag: "Africa/Zimbabwe.png" },

  // Asia
  { country: "Afghanistan", capital: "Kabul", flag: "Asia/Afghanistan.png" },
  { country: "Bahrain", capital: "Manama", flag: "Asia/Bahrain .png" },
  { country: "Bangladesh", capital: "Dhaka", flag: "Asia/Bangladesh.png" },
  { country: "Bhutan", capital: "Thimphu", flag: "Asia/Bhutan .png" },
  { country: "Brunei", capital: "Bandar Seri Begawan", flag: "Asia/Brunei.png" },
  { country: "Cambodia", capital: "Phnom Penh", flag: "Asia/Cambodia.png" },
  { country: "China", capital: "Beijing", flag: "Asia/China.png" },
  { country: "East Timor", capital: "Dili", flag: "Asia/EastTimor.png" },
  { country: "India", capital: "New Delhi", flag: "Asia/India.png" },
  { country: "Indonesia", capital: "Jakarta", flag: "Asia/Indonesia.png" },
  { country: "Iran", capital: "Tehran", flag: "Asia/Iran.png" },
  { country: "Iraq", capital: "Baghdad", flag: "Asia/Iraq.png" },
  { country: "Israel", capital: "Jerusalem", flag: "Asia/Israel.png" },
  { country: "Japan", capital: "Tokyo", flag: "Asia/Japan.png" },
  { country: "Jordan", capital: "Amman", flag: "Asia/Jordan.png" },
  { country: "Kuwait", capital: "Kuwait City", flag: "Asia/Kuwait.png" },
  { country: "Kyrgyzstan", capital: "Bishkek", flag: "Asia/Kyrgyzstan.png" },
  { country: "Laos", capital: "Vientiane", flag: "Asia/Laos.png" },
  { country: "Lebanon", capital: "Beirut", flag: "Asia/Lebanon.png" },
  { country: "Malaysia", capital: "Kuala Lumpur", flag: "Asia/Malaysia.png" },
  { country: "Maldives", capital: "Malé", flag: "Asia/Maldives.png" },
  { country: "Mongolia", capital: "Ulaanbaatar", flag: "Asia/Mongolia.png" },
  { country: "Myanmar", capital: "Naypyidaw", flag: "Asia/Myanmar.png" },
  { country: "Nepal", capital: "Kathmandu", flag: "Asia/Nepal.png" },
  { country: "North Korea", capital: "Pyongyang", flag: "Asia/NorthKorea.png" },
  { country: "Oman", capital: "Muscat", flag: "Asia/Oman.png" },
  { country: "Pakistan", capital: "Islamabad", flag: "Asia/Pakistan.png" },
  { country: "Palestine", capital: "Ramallah", flag: "Asia/Palestine.png" },
  { country: "Philippines", capital: "Manila", flag: "Asia/Philippines.png" },
  { country: "Qatar", capital: "Doha", flag: "Asia/Qatar.png" },
  { country: "Saudi Arabia", capital: "Riyadh", flag: "Asia/SaudiArabia.png" },
  { country: "Singapore", capital: "Singapore", flag: "Asia/Singapore.png" },
  { country: "South Korea", capital: "Seoul", flag: "Asia/SouthKorea.png" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", flag: "Asia/SriLanka.png" },
  { country: "Syria", capital: "Damascus", flag: "Asia/Syria.png" },
  { country: "Tajikistan", capital: "Dushanbe", flag: "Asia/Tajikistan.png" },
  { country: "Thailand", capital: "Bangkok", flag: "Asia/Thailand.png" },
  { country: "Turkmenistan", capital: "Ashgabat", flag: "Asia/Turkmenistan.png" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", flag: "Asia/UnitedArabEmirates.png" },
  { country: "Uzbekistan", capital: "Tashkent", flag: "Asia/Uzbekistan.png" },
  { country: "Vietnam", capital: "Hanoi", flag: "Asia/Vietnam.png" },
  { country: "Yemen", capital: "Sana'a", flag: "Asia/Yemen.png" },

  // Oceania
  { country: "Australia", capital: "Canberra", flag: "Oceania/Australia.png" },
  { country: "Fiji", capital: "Suva", flag: "Oceania/Fiji.png" },
  { country: "Kiribati", capital: "Tarawa", flag: "Oceania/Kiribati.png" },
  { country: "Marshall Islands", capital: "Majuro", flag: "Asia/MarshallIslands.png" },
  { country: "Micronesia", capital: "Palikir", flag: "Oceania/Micronesia.png" },
  { country: "Nauru", capital: "Yaren", flag: "Oceania/Nauru.png" },
  { country: "New Zealand", capital: "Wellington", flag: "Oceania/NewZealand.png" },
  { country: "Palau", capital: "Ngerulmud", flag: "Oceania/Palau.png" },
  { country: "Papua New Guinea", capital: "Port Moresby", flag: "Oceania/PapuaNewGuinea.png" },
  { country: "Samoa", capital: "Apia", flag: "Oceania/Samoa.png" },
  { country: "Solomon Islands", capital: "Honiara", flag: "Oceania/SolomonIslands.png" },
  { country: "Tonga", capital: "Nukuʻalofa", flag: "Oceania/Tonga.png" },
  { country: "Tuvalu", capital: "Funafuti", flag: "Oceania/Tuvalu.png" },
  { country: "Vanuatu", capital: "Port Vila", flag: "Oceania/Vanuatu.png" }
];